import { createContext, useCallback, useContext, useLayoutEffect, useMemo, useState, type ReactNode } from "react";
import { setFormattingLanguage } from "../lib/format";

export type AppLanguage = "en" | "ar";
type TranslationValues = Record<string, string | number>;

const arabic: Record<string, string> = {
  "Personal finance": "المالية الشخصية",
  "Dashboard": "لوحة المعلومات",
  "Salary / Income": "الراتب / الدخل",
  "Income": "الدخل",
  "Expenses": "المصروفات",
  "Savings": "المدخرات",
  "Goals": "الأهداف",
  "Transactions": "المعاملات",
  "Settings": "الإعدادات",
  "Workspace": "مساحة العمل",
  "Private by design": "خصوصية من الأساس",
  "Your data is isolated with RLS": "بياناتك معزولة بسياسات RLS",
  "Open menu": "فتح القائمة",
  "Close profile menu": "إغلاق قائمة الملف الشخصي",
  "Account settings": "إعدادات الحساب",
  "Sign out": "تسجيل الخروج",
  "Use light mode": "استخدام الوضع الفاتح",
  "Use dark mode": "استخدام الوضع الداكن",
  "Appearance updated": "تم تحديث المظهر",
  "Couldn’t load your workspace": "تعذر تحميل مساحة العمل",
  "Check your connection and Supabase setup, then try again.": "تحقق من اتصالك وإعداد Supabase ثم حاول مرة أخرى.",
  "Try again": "إعادة المحاولة",
  "Delete": "حذف",
  "Cancel": "إلغاء",
  "Color": "اللون",
  "Clear search": "مسح البحث",
  "Sort order": "ترتيب الفرز",
  "Dismiss notification": "إغلاق الإشعار",
  "Something went wrong. Please try again.": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",

  "Money, without the fog": "أموالك بوضوح",
  "See where your money really goes.": "اعرف أين تذهب أموالك فعلاً.",
  "One calm, private workspace for income, spending, savings, and the goals that matter.": "مساحة هادئة وخاصة للدخل والمصروفات والمدخرات والأهداف المهمة.",
  "Available balance": "الرصيد المتاح",
  "+12.4% this month": "+12.4% هذا الشهر",
  "this month": "هذا الشهر",
  "Japan trip": "رحلة اليابان",
  "Yours alone": "ملكك وحدك",
  "Protected row by row": "حماية لكل سجل",
  "Encrypted authentication": "مصادقة مشفرة",
  "Private by default": "خاص افتراضياً",
  "Cloud sync": "مزامنة سحابية",
  "Account access": "الدخول إلى الحساب",
  "Log in": "تسجيل الدخول",
  "Sign up": "إنشاء حساب",
  "SECURE SIGN IN": "تسجيل دخول آمن",
  "NEW TO NORTHSTAR": "جديد في نورث ستار",
  "ACCOUNT RECOVERY": "استعادة الحساب",
  "Welcome back.": "مرحباً بعودتك.",
  "Create your private workspace.": "أنشئ مساحتك الخاصة.",
  "Reset your password.": "إعادة تعيين كلمة المرور.",
  "Sign in to continue to your financial workspace.": "سجّل الدخول للمتابعة إلى مساحتك المالية.",
  "Start tracking your money with an account protected by Supabase Auth.": "ابدأ متابعة أموالك بحساب محمي عبر Supabase Auth.",
  "Enter your email and we’ll send a secure reset link.": "أدخل بريدك الإلكتروني وسنرسل رابط إعادة تعيين آمناً.",
  "Full name": "الاسم الكامل",
  "Your full name": "اسمك الكامل",
  "Email address": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Enter your password": "أدخل كلمة المرور",
  "At least 8 characters": "8 أحرف على الأقل",
  "Confirm password": "تأكيد كلمة المرور",
  "Repeat your password": "أعد كتابة كلمة المرور",
  "Forgot password?": "نسيت كلمة المرور؟",
  "Create account": "إنشاء الحساب",
  "Send reset link": "إرسال رابط الاستعادة",
  "Back to login": "العودة لتسجيل الدخول",
  "Show password": "إظهار كلمة المرور",
  "Hide password": "إخفاء كلمة المرور",
  "Protected by Supabase Auth": "محمي بواسطة Supabase Auth",
  "Your data stays yours.": "بياناتك تبقى ملكك.",
  "Passwords are securely managed by Supabase; Row Level Security keeps every financial record private to your account.": "تُدار كلمات المرور بأمان عبر Supabase، وتضمن سياسات أمان الصفوف بقاء كل سجل مالي خاصاً بحسابك.",
  "By continuing, you agree to use Northstar for personal financial organization. Northstar does not provide financial advice.": "بالمتابعة، توافق على استخدام نورث ستار لتنظيم أموالك الشخصية. لا يقدم نورث ستار نصائح مالية.",
  "Connect Supabase to continue": "اربط Supabase للمتابعة",
  "Add the project URL and publishable key to .env.local, then restart the development server.": "أضف رابط المشروع والمفتاح العام إلى ‎.env.local ثم أعد تشغيل خادم التطوير.",
  "Enter your personal email address.": "أدخل بريدك الإلكتروني الشخصي.",
  "Enter your full name.": "أدخل اسمك الكامل.",
  "Use a password with at least 8 characters.": "استخدم كلمة مرور من 8 أحرف على الأقل.",
  "The passwords do not match.": "كلمتا المرور غير متطابقتين.",
  "That email or password is incorrect.": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "Confirm your email address before signing in.": "أكد بريدك الإلكتروني قبل تسجيل الدخول.",
  "An account already exists for that email. Try signing in instead.": "يوجد حساب بهذا البريد. جرّب تسجيل الدخول.",
  "Too many attempts. Please wait a moment and try again.": "محاولات كثيرة. انتظر قليلاً ثم حاول مجدداً.",
  "We sent a confirmation link to {email}. Open it to activate your account.": "أرسلنا رابط تأكيد إلى {email}. افتحه لتفعيل حسابك.",
  "If an account exists for {email}, a secure password-reset link is on its way.": "إذا كان هناك حساب للبريد {email} فسيصلك رابط آمن لإعادة تعيين كلمة المرور.",
  "Confirming your account…": "جارٍ تأكيد حسابك…",
  "Securely verifying your email and opening your workspace.": "جارٍ التحقق من بريدك بأمان وفتح مساحة العمل.",
  "Verifying your reset link…": "جارٍ التحقق من رابط الاستعادة…",
  "Checking your secure recovery session.": "جارٍ فحص جلسة الاستعادة الآمنة.",
  "Password updated.": "تم تحديث كلمة المرور.",
  "Your new password is active and your current session remains securely signed in.": "كلمة المرور الجديدة فعالة وجلستك الحالية ما زالت مسجلة بأمان.",
  "Continue to dashboard": "المتابعة إلى لوحة المعلومات",
  "This reset link is no longer valid.": "رابط الاستعادة لم يعد صالحاً.",
  "Reset links expire and can only be used once. Request a fresh link from the login page.": "تنتهي صلاحية روابط الاستعادة ولا تُستخدم إلا مرة واحدة. اطلب رابطاً جديداً من صفحة الدخول.",
  "Return to login": "العودة لتسجيل الدخول",
  "SECURE ACCOUNT RECOVERY": "استعادة آمنة للحساب",
  "Create a new password.": "أنشئ كلمة مرور جديدة.",
  "Choose a strong password you haven’t used for this account before.": "اختر كلمة مرور قوية لم تستخدمها لهذا الحساب من قبل.",
  "New password": "كلمة المرور الجديدة",
  "Confirm new password": "تأكيد كلمة المرور الجديدة",
  "Update password": "تحديث كلمة المرور",
  "Restoring your workspace…": "جارٍ استعادة مساحة العمل…",
  "Your secure session is being refreshed.": "جارٍ تحديث جلستك الآمنة.",

  "FINANCIAL OVERVIEW": "نظرة مالية عامة",
  "Good morning, {name}.": "صباح الخير، {name}.",
  "Good afternoon, {name}.": "مساء الخير، {name}.",
  "Good evening, {name}.": "مساء الخير، {name}.",
  "there": "بك",
  "A clear view of everything you’ve earned, spent, and set aside.": "نظرة واضحة على كل ما كسبته وأنفقته وادخرته.",
  "Add money activity": "إضافة حركة مالية",
  "Total income": "إجمالي الدخل",
  "Total expenses": "إجمالي المصروفات",
  "Total savings": "إجمالي المدخرات",
  "Expenses + savings": "المصروفات + المدخرات",
  "Income − expenses − savings & goals": "الدخل − المصروفات − المدخرات والأهداف",
  "Total income already committed": "إجمالي الدخل المخصص بالفعل",
  "{count} income entries": "{count} إدخالات دخل",
  "{count} recorded expenses": "{count} مصروفات مسجلة",
  "{amount} is in goals": "{amount} مخصص للأهداف",
  "6-MONTH TREND": "اتجاه 6 أشهر",
  "Money flow": "التدفق المالي",
  "Your trend starts here": "يبدأ اتجاهك من هنا",
  "Add income, expenses, or savings activity to see monthly patterns.": "أضف دخلاً أو مصروفات أو مدخرات لرؤية الأنماط الشهرية.",
  "THIS MONTH": "هذا الشهر",
  "On track": "على المسار",
  "Over budget": "تجاوز الميزانية",
  "Net cash flow": "صافي التدفق النقدي",
  "Compared with last month": "مقارنة بالشهر الماضي",
  "ALL-TIME BREAKDOWN": "التوزيع الإجمالي",
  "Spending by category": "الإنفاق حسب الفئة",
  "View expenses": "عرض المصروفات",
  "Total spent": "إجمالي المنفق",
  "No expenses yet": "لا توجد مصروفات بعد",
  "Record your first expense to build a category breakdown.": "سجل أول مصروف لبناء توزيع حسب الفئات.",
  "LATEST ACTIVITY": "أحدث الأنشطة",
  "Recent transactions": "أحدث المعاملات",
  "See all": "عرض الكل",
  "No transactions yet": "لا توجد معاملات بعد",
  "Your income, expenses, transfers, and allocations will appear here.": "سيظهر هنا دخلك ومصروفاتك وتحويلاتك ومخصصاتك.",

  "MONEY IN": "الأموال الداخلة",
  "Salary & income": "الراتب والدخل",
  "Track every source of income and keep a clean history of what you earn.": "تابع كل مصدر دخل واحتفظ بسجل واضح لما تكسبه.",
  "Manage sources": "إدارة المصادر",
  "Add income": "إضافة دخل",
  "Showing": "المعروض",
  "Filtered total": "الإجمالي المصفى",
  "Income sources": "مصادر الدخل",
  "Search income…": "البحث في الدخل…",
  "All sources": "كل المصادر",
  "All months": "كل الأشهر",
  "Newest first": "الأحدث أولاً",
  "Oldest first": "الأقدم أولاً",
  "Highest amount": "أعلى مبلغ",
  "Lowest amount": "أقل مبلغ",
  "Name A–Z": "الاسم أبجدياً",
  "Source": "المصدر",
  "Date received": "تاريخ الاستلام",
  "Amount": "المبلغ",
  "Actions": "الإجراءات",
  "No notes": "لا توجد ملاحظات",
  "Deleted source": "مصدر محذوف",
  "Income actions": "إجراءات الدخل",
  "Close menu": "إغلاق القائمة",
  "Edit": "تعديل",
  "No matching income": "لا يوجد دخل مطابق",
  "Add your first income": "أضف أول دخل",
  "Try adjusting your search or filters.": "جرّب تعديل البحث أو عوامل التصفية.",
  "Salary, freelance work, gifts—keep every source in one clear view.": "الراتب والعمل الحر والهدايا—احتفظ بكل مصدر في عرض واضح.",
  "Edit income": "تعديل الدخل",
  "INCOME ENTRY": "إدخال الدخل",
  "Save changes": "حفظ التغييرات",
  "Income source": "مصدر الدخل",
  "Select a source": "اختر مصدراً",
  "Description": "الوصف",
  "e.g. August salary": "مثال: راتب آب",
  "Notes": "ملاحظات",
  "Optional details": "تفاصيل اختيارية",
  "Delete income entry?": "حذف إدخال الدخل؟",
  "This will permanently remove “{name}” and its matching transaction. Your totals will update immediately.": "سيؤدي هذا إلى حذف «{name}» ومعاملته المرتبطة نهائياً. ستتحدث الإجماليات فوراً.",
  "ORGANIZE INCOME": "تنظيم الدخل",
  "Your sources": "مصادرك",
  "EDIT SOURCE": "تعديل المصدر",
  "NEW SOURCE": "مصدر جديد",
  "Create a source": "إنشاء مصدر",
  "Source name": "اسم المصدر",
  "e.g. Consulting": "مثال: استشارات",
  "Create source": "إنشاء المصدر",
  "Delete income source?": "حذف مصدر الدخل؟",

  "MONEY OUT": "الأموال الخارجة",
  "Capture everyday spending, find patterns, and keep every category under control.": "سجل الإنفاق اليومي واكتشف الأنماط وتحكم بكل فئة.",
  "Add expense": "إضافة مصروف",
  "Filtered spend": "الإنفاق المصفى",
  "Largest expense": "أكبر مصروف",
  "Search merchant or notes…": "البحث في التاجر أو الملاحظات…",
  "All categories": "كل الفئات",
  "Merchant A–Z": "التاجر أبجدياً",
  "Merchant": "التاجر",
  "Category": "الفئة",
  "Date spent": "تاريخ الإنفاق",
  "Uncategorized": "غير مصنف",
  "Expense actions": "إجراءات المصروف",
  "No matching expenses": "لا توجد مصروفات مطابقة",
  "No expenses recorded": "لا توجد مصروفات مسجلة",
  "Add a purchase or bill to start understanding where your money goes.": "أضف عملية شراء أو فاتورة لتبدأ بفهم أين تذهب أموالك.",
  "Edit expense": "تعديل المصروف",
  "EXPENSE ENTRY": "إدخال المصروف",
  "Select a category": "اختر فئة",
  "Merchant / description": "التاجر / الوصف",
  "e.g. Corner Market": "مثال: السوق المحلي",
  "Delete expense?": "حذف المصروف؟",
  "This permanently removes “{name}” and its matching transaction. Your balance will update immediately.": "سيؤدي هذا إلى حذف «{name}» ومعاملته المرتبطة نهائياً. سيتحدث رصيدك فوراً.",

  "SET MONEY ASIDE": "خصص المال جانباً",
  "Create dedicated accounts, move money safely, and see exactly what you’ve allocated.": "أنشئ حسابات مخصصة وانقل المال بأمان واعرف ما خصصته بدقة.",
  "Transfer": "تحويل",
  "New account": "حساب جديد",
  "Total in savings accounts": "الإجمالي في حسابات الادخار",
  "Transfers never change this total or your available balance.": "التحويلات لا تغير هذا الإجمالي ولا رصيدك المتاح.",
  "Deposit": "إيداع",
  "Withdraw": "سحب",
  "Search savings accounts…": "البحث في حسابات الادخار…",
  "All account types": "كل أنواع الحسابات",
  "Money market": "سوق المال",
  "Investment": "استثمار",
  "Cash": "نقد",
  "Date created": "تاريخ الإنشاء",
  "Highest balance": "أعلى رصيد",
  "Lowest balance": "أقل رصيد",
  "Account actions": "إجراءات الحساب",
  "Edit details": "تعديل التفاصيل",
  "Personal account": "حساب شخصي",
  "Current balance": "الرصيد الحالي",
  "No matching accounts": "لا توجد حسابات مطابقة",
  "Build your savings system": "أنشئ نظام ادخارك",
  "Try changing your search or account-type filter.": "جرّب تغيير البحث أو عامل تصفية نوع الحساب.",
  "Create separate accounts for an emergency fund, investments, or anything you want to protect.": "أنشئ حسابات منفصلة للطوارئ أو الاستثمارات أو أي شيء تريد حمايته.",
  "Edit savings account": "تعديل حساب الادخار",
  "New savings account": "حساب ادخار جديد",
  "ACCOUNT DETAILS": "تفاصيل الحساب",
  "Account name": "اسم الحساب",
  "e.g. Emergency fund": "مثال: صندوق الطوارئ",
  "Account type": "نوع الحساب",
  "Institution": "المؤسسة",
  "Optional": "اختياري",
  "Deposit to savings": "إيداع في المدخرات",
  "Withdraw from savings": "سحب من المدخرات",
  "Transfer between accounts": "تحويل بين الحسابات",
  "MONEY MOVEMENT": "حركة الأموال",
  "Record deposit": "تسجيل الإيداع",
  "Record withdrawal": "تسجيل السحب",
  "Transfer money": "تحويل المال",
  "From account": "من الحساب",
  "Savings account": "حساب الادخار",
  "Select account": "اختر حساباً",
  "To account": "إلى الحساب",
  "Select destination": "اختر الوجهة",
  "One transfer transaction moves the money. It does not change total savings or available balance.": "تنقل معاملة تحويل واحدة المال دون تغيير إجمالي المدخرات أو الرصيد المتاح.",
  "Amount cannot exceed {amount}.": "لا يمكن أن يتجاوز المبلغ {amount}.",
  "Choose two different accounts.": "اختر حسابين مختلفين.",
  "Delete savings account?": "حذف حساب الادخار؟",

  "PLAN WITH PURPOSE": "خطط بهدف",
  "Financial goals": "الأهداف المالية",
  "Turn the things you care about into clear, measurable progress.": "حوّل ما يهمك إلى تقدم واضح وقابل للقياس.",
  "New goal": "هدف جديد",
  "Allocated to goals": "المخصص للأهداف",
  "Money here is already deducted from available balance.": "هذا المال مخصوم بالفعل من الرصيد المتاح.",
  "Active goals": "الأهداف النشطة",
  "Completed": "مكتملة",
  "Search goals…": "البحث في الأهداف…",
  "All goals": "كل الأهداف",
  "Active": "نشطة",
  "Target date": "تاريخ الهدف",
  "Highest target": "أعلى هدف",
  "Lowest target": "أقل هدف",
  "Goal actions": "إجراءات الهدف",
  "Edit goal": "تعديل الهدف",
  "Goal reached": "تم تحقيق الهدف",
  "In progress": "قيد التقدم",
  "{count} days left": "متبقي {count} يوم",
  "Past due": "متأخر",
  "No deadline—go at your pace": "بلا موعد نهائي—تقدم بوتيرتك",
  "{amount} saved in total": "تم ادخار {amount} إجمالاً",
  "{remaining} left of {target}": "متبقي {remaining} من {target}",
  "Add money": "إضافة مال",
  "No matching goals": "لا توجد أهداف مطابقة",
  "Give your money a destination": "امنح أموالك وجهة",
  "Try adjusting your search or status filter.": "جرّب تعديل البحث أو عامل تصفية الحالة.",
  "Create a goal for a trip, a home, an emergency fund, or the next thing that matters.": "أنشئ هدفاً لرحلة أو منزل أو صندوق طوارئ أو أي شيء مهم قادم.",
  "Create a goal": "إنشاء هدف",
  "Edit financial goal": "تعديل الهدف المالي",
  "New financial goal": "هدف مالي جديد",
  "GOAL DETAILS": "تفاصيل الهدف",
  "Create goal": "إنشاء الهدف",
  "Goal name": "اسم الهدف",
  "e.g. New home": "مثال: منزل جديد",
  "e.g. Japan trip": "مثال: رحلة اليابان",
  "Target amount": "المبلغ المستهدف",
  "Target date (optional)": "تاريخ الهدف (اختياري)",
  "Add money to a goal": "إضافة مال إلى هدف",
  "Withdraw from a goal": "سحب من هدف",
  "GOAL ACTIVITY": "حركة الهدف",
  "Withdraw money": "سحب المال",
  "Financial goal": "الهدف المالي",
  "Select goal": "اختر هدفاً",
  "Delete financial goal?": "حذف الهدف المالي؟",

  "COMPLETE LEDGER": "السجل الكامل",
  "Every financial event in one audit-friendly timeline—without counting transfers twice.": "كل حدث مالي في تسلسل واضح للتدقيق—من دون احتساب التحويلات مرتين.",
  "Export CSV": "تصدير CSV",
  "Add activity": "إضافة حركة",
  "What would you like to record?": "ماذا تريد أن تسجل؟",
  "Salary or other earnings": "راتب أو أرباح أخرى",
  "Expense": "مصروف",
  "Purchase, bill, or payment": "شراء أو فاتورة أو دفعة",
  "Savings activity": "حركة المدخرات",
  "Deposit, withdraw, or transfer": "إيداع أو سحب أو تحويل",
  "Goal activity": "حركة الهدف",
  "Add or withdraw goal money": "إضافة أو سحب مال الهدف",
  "Transactions shown": "المعاملات المعروضة",
  "Inflows": "التدفقات الداخلة",
  "Outflows": "التدفقات الخارجة",
  "Transfers between savings accounts are neutral and excluded from both figures.": "التحويلات بين حسابات الادخار محايدة ومستبعدة من الرقمين.",
  "Search transactions…": "البحث في المعاملات…",
  "All transaction types": "كل أنواع المعاملات",
  "All savings activity": "كل حركات المدخرات",
  "All goal activity": "كل حركات الأهداف",
  "Savings deposits": "إيداعات المدخرات",
  "Savings withdrawals": "سحوبات المدخرات",
  "Savings transfers": "تحويلات المدخرات",
  "Goal deposits": "إيداعات الأهداف",
  "Goal withdrawals": "سحوبات الأهداف",
  "Activity": "الحركة",
  "No matching transactions": "لا توجد معاملات مطابقة",
  "Your ledger is ready": "سجلك جاهز",
  "Add income, an expense, savings, or a goal contribution and it will appear here automatically.": "أضف دخلاً أو مصروفاً أو ادخاراً أو مساهمة في هدف وستظهر هنا تلقائياً.",
  "Savings deposit": "إيداع مدخرات",
  "Savings withdrawal": "سحب مدخرات",
  "Savings transfer": "تحويل مدخرات",
  "Goal deposit": "إيداع هدف",
  "Goal withdrawal": "سحب هدف",

  "YOUR WORKSPACE": "مساحة عملك",
  "Personalize Northstar and manage how your financial data is organized.": "خصص نورث ستار وتحكم في كيفية تنظيم بياناتك المالية.",
  "Profile": "الملف الشخصي",
  "Your account identity and display preferences.": "هوية حسابك وتفضيلات العرض.",
  "Email and password are securely managed by Supabase Auth": "يُدار البريد وكلمة المرور بأمان عبر Supabase Auth",
  "Display name": "اسم العرض",
  "Currency": "العملة",
  "Language": "اللغة",
  "English": "الإنجليزية",
  "Arabic": "العربية",
  "Appearance": "المظهر",
  "Choose how Northstar looks on this account.": "اختر مظهر نورث ستار لهذا الحساب.",
  "Light": "فاتح",
  "Dark": "داكن",
  "System": "النظام",
  "Changes sync to every device signed into your account.": "تتزامن التغييرات مع كل جهاز مسجل بحسابك.",
  "Save settings": "حفظ الإعدادات",
  "Settings saved": "تم حفظ الإعدادات",
  "Expense categories": "فئات المصروفات",
  "Create a spending system that matches your life.": "أنشئ نظام إنفاق يناسب حياتك.",
  "New category": "فئة جديدة",
  "Edit expense category": "تعديل فئة المصروف",
  "New expense category": "فئة مصروف جديدة",
  "CATEGORY DETAILS": "تفاصيل الفئة",
  "Create category": "إنشاء الفئة",
  "Category name": "اسم الفئة",
  "e.g. Pets": "مثال: الحيوانات الأليفة",
  "Icon": "الأيقونة",
  "Delete expense category?": "حذف فئة المصروف؟",
  "Data & security": "البيانات والأمان",
  "Your records are protected by Supabase Auth and per-user Row Level Security.": "سجلاتك محمية عبر Supabase Auth وسياسات أمان الصفوف لكل مستخدم.",
  "Export a complete backup": "تصدير نسخة احتياطية كاملة",
  "Download your profile and all financial records as a portable JSON file.": "نزّل ملفك الشخصي وكل السجلات المالية كملف JSON قابل للنقل.",
  "Download backup": "تنزيل النسخة الاحتياطية",
  "Sign out of this browser": "تسجيل الخروج من هذا المتصفح",
  "Your cloud data remains safe and available when you sign in again.": "تبقى بياناتك السحابية آمنة ومتاحة عند تسجيل الدخول مجدداً.",

  "Close": "إغلاق",
  "Clear": "مسح",
  "entries": "إدخالات",
  "expenses": "مصروفات",
  "this entry": "هذا الإدخال",
  "this source": "هذا المصدر",
  "this expense": "هذا المصروف",
  "this account": "هذا الحساب",
  "this goal": "هذا الهدف",
  "Edit {name}": "تعديل {name}",
  "Delete {name}": "حذف {name}",
  "Save source": "حفظ المصدر",
  "Existing entries for “{name}” will remain in your history and become uncategorized.": "ستبقى الإدخالات الحالية للمصدر «{name}» في سجلك وستصبح غير مصنفة.",
  "“{name}” still has {amount}. Withdraw or transfer the full balance before deleting it.": "ما زال حساب «{name}» يحتوي على {amount}. اسحب الرصيد بالكامل أو حوّله قبل الحذف.",
  "This removes “{name}”. Past transactions stay in your history.": "سيؤدي هذا إلى حذف «{name}». تبقى المعاملات السابقة في سجلك.",
  "“{name}” still has {amount} allocated. Withdraw that money before deleting the goal.": "ما زال مبلغ {amount} مخصصاً للهدف «{name}». اسحب المال قبل حذف الهدف.",
  "{amount} saved": "تم ادخار {amount}",
  "Most progress": "الأكثر تقدماً",
  "Largest target": "أكبر هدف",
  "Date": "التاريخ",
  "Type": "النوع",
  "Close add menu": "إغلاق قائمة الإضافة",

  "Income entry updated": "تم تحديث إدخال الدخل",
  "Income added": "تمت إضافة الدخل",
  "Income entry deleted": "تم حذف إدخال الدخل",
  "Income source updated": "تم تحديث مصدر الدخل",
  "Income source created": "تم إنشاء مصدر الدخل",
  "Income source deleted": "تم حذف مصدر الدخل",
  "Expense updated": "تم تحديث المصروف",
  "Expense added": "تمت إضافة المصروف",
  "Expense deleted": "تم حذف المصروف",
  "Savings account updated": "تم تحديث حساب الادخار",
  "Savings account created": "تم إنشاء حساب الادخار",
  "Savings account deleted": "تم حذف حساب الادخار",
  "Savings deposit recorded": "تم تسجيل إيداع المدخرات",
  "Savings withdrawal recorded": "تم تسجيل سحب المدخرات",
  "Savings transferred": "تم تحويل المدخرات",
  "Goal updated": "تم تحديث الهدف",
  "Goal created": "تم إنشاء الهدف",
  "Goal deleted": "تم حذف الهدف",
  "Goal contribution recorded": "تم تسجيل مساهمة الهدف",
  "Goal withdrawal recorded": "تم تسجيل سحب الهدف",
  "Category updated": "تم تحديث الفئة",
  "Category created": "تم إنشاء الفئة",
  "Category deleted": "تم حذف الفئة",

  "US Dollar": "الدولار الأمريكي",
  "Euro": "اليورو",
  "British Pound": "الجنيه الإسترليني",
  "Canadian Dollar": "الدولار الكندي",
  "Australian Dollar": "الدولار الأسترالي",
  "Japanese Yen": "الين الياباني",
  "Indian Rupee": "الروبية الهندية",
  "Pakistani Rupee": "الروبية الباكستانية",
  "UAE Dirham": "الدرهم الإماراتي",
  "Iraqi Dinar": "الدينار العراقي",
  "Food & dining": "الطعام والمطاعم",
  "Bills & utilities": "الفواتير والخدمات",
  "Money Market": "سوق المال",
  "Savings Deposit": "إيداع مدخرات",
  "Savings Withdrawal": "سحب مدخرات",
  "Savings Transfer": "تحويل مدخرات",
  "Goal Deposit": "إيداع هدف",
  "Goal Withdrawal": "سحب هدف",
  "Account": "الحساب",
  "house": "منزل",
  "utensils": "طعام",
  "car": "سيارة",
  "shopping bag": "تسوق",
  "heart pulse": "صحة",
  "receipt": "إيصال",
  "sparkles": "ترفيه",
  "shapes": "أخرى",

  "Salary": "الراتب",
  "Freelance": "عمل حر",
  "Other": "أخرى",
  "Housing": "السكن",
  "Food": "الطعام",
  "Transport": "النقل",
  "Utilities": "الخدمات",
  "Health": "الصحة",
  "Entertainment": "الترفيه",
  "Shopping": "التسوق",
  "Education": "التعليم",
  "savings": "ادخار",
  "money market": "سوق المال",
  "investment": "استثمار",
  "cash": "نقد",
  "income": "دخل",
  "expense": "مصروف",
  "savings deposit": "إيداع مدخرات",
  "savings withdrawal": "سحب مدخرات",
  "savings transfer": "تحويل مدخرات",
  "goal deposit": "إيداع هدف",
  "goal withdrawal": "سحب هدف",
};

interface LanguageContextValue {
  language: AppLanguage;
  locale: "en-US" | "ar-IQ";
  isRtl: boolean;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string, values?: TranslationValues) => string;
  number: (value: number) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function initialLanguage(): AppLanguage {
  const saved = window.localStorage.getItem("northstar-language");
  if (saved === "ar" || saved === "en") return saved;
  return navigator.language.toLowerCase().startsWith("ar") ? "ar" : "en";
}

function applyDocumentLanguage(language: AppLanguage) {
  setFormattingLanguage(language);
  document.documentElement.lang = language;
  document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    const initial = initialLanguage();
    applyDocumentLanguage(initial);
    return initial;
  });
  const locale: LanguageContextValue["locale"] = language === "ar" ? "ar-IQ" : "en-US";
  useLayoutEffect(() => applyDocumentLanguage(language), [language]);

  const setLanguage = useCallback((next: AppLanguage) => {
    window.localStorage.setItem("northstar-language", next);
    applyDocumentLanguage(next);
    setLanguageState(next);
  }, []);

  const t = useCallback((key: string, values?: TranslationValues) => {
    let text = language === "ar" ? arabic[key] || key : key;
    if (values) {
      for (const [name, value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, String(value));
    }
    return text;
  }, [language]);

  const number = useCallback((value: number) => new Intl.NumberFormat(locale).format(value), [locale]);
  const value = useMemo(() => ({ language, locale, isRtl: language === "ar", setLanguage, t, number }), [language, locale, number, setLanguage, t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
